env:
  ACCOUNT_ID_DEV: '123'
  ACCOUNT_ID_STAGING: '321'
  ACCOUNT_ID_PRODUCTION: '1234567'
  ASSUME_ROLE: MyBatchUploadRole

steps:
  - block: ":file_cabinet: Paste merchants information in dev"
    fields:
      - text: "Merchants information in TSV format"
        key: MERCHANTS_INFO
        required: true

  - label: "Sending messages to dev"
    env:
      TARGET_ACCOUNT_ID: ${ACCOUNT_ID_DEV}
    plugins:
      - docker-compose#v3.0.3:
          run: batch-publish-message
          config: .buildkite/docker-compose.yml
      - ACloudGuru/metadata-env:
          keys:
            - MERCHANTS_INFO