steps:
  - block: "Upload csv file content"
    fields:
      - text: "CSV File"
        key: CSV_FILE
        required: true

  - label: "Parsing CSV file"
    command: .buildkite/scripts/parse.sh
    plugins:
      - ACloudGuru/metadata-env:
          keys:
            - CSV_FILE

